// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4H94qNMnA37gpBXHfT37McIKwYaG8sqs',
    appId: '1:248514443235:android:1076b78926d490768812d6',
    messagingSenderId: '248514443235',
    projectId: 'ivf-project-9993f',
    databaseURL: 'https://ivf-project-9993f-default-rtdb.firebaseio.com',
    storageBucket: 'ivf-project-9993f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYreRy_PvnvkezLm14g9W2-0rqbsEOms',
    appId: '1:248514443235:ios:607b6b7cb1723f1e8812d6',
    messagingSenderId: '248514443235',
    projectId: 'ivf-project-9993f',
    databaseURL: 'https://ivf-project-9993f-default-rtdb.firebaseio.com',
    storageBucket: 'ivf-project-9993f.appspot.com',
    iosClientId: '248514443235-a4gero3e2op6pmvgqnou6kclfl0fs37c.apps.googleusercontent.com',
    iosBundleId: 'com.ivfproject.ivfProject',
  );
}
